name: CI

on:
  push:
    branches:
    - develop
    - feature/*
    - hotfix/*

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}
      - name: Get poetry
        run: |
          pip install poetry==1.1.6
      - name: install project dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install
      - name: Check code formatting
        run: |
          black --check ./brsus/ --exclude __init__.py --verbose
      - name: Check import orders
        run: |
          isort --check ./brsus/ --skip __init__.py --gitignore --dont-follow-links --verbose
      - name: Linter
        run: |
          pylama ./brsus/ ./tests/ --skip brsus/**/__init__.py
      - name: Run tests
        run: |
          pytest ./tests/ --verbose --color=yes --code-highlight=yes
